---
name: Build package and deploy to Github pages
on:
  - push
  - workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - run: apt-get update
      - name: Install build dependencies
        run: apt-get install -yq build-essential devscripts
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - run: ls -la
      - name: Build the DEB binary package
        run: dpkg-buildpackage -uc -us -b
      - run: ls -la ../ ./
      - run: ls -la /__w/actions-deb-minimal/ /__w/actions-deb-minimal/actions-deb-minimal
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: my-deb
          path: '/__w/actions-deb-minimal/*.deb'
          retention-days: 5
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8
      - run: ls -la
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
